CREATE DATABASE QUANLINHANVIEN
use QUANLINHANVIEN

CREATE TABLE PHONGBAN(
	TENPHG CHAR(10) NOT NULL,
	MAPHG INT,
	TRPHG CHAR(3),
	NG_NHANCHUC DATE,
	CONSTRAINT PK_PB_MAPHG PRIMARY KEY(MAPHG)
)

CREATE TABLE NHANVIEN(
	HONV CHAR(20),
	TENLOT CHAR(20),
	TENNV CHAR(20),
	MANV CHAR(3) NOT NULL,
	NGSINH DATE,
	PHAI CHAR(3),
	LUONG FLOAT,
	DCHI CHAR(100),
	MA_NQL CHAR(3),
	PHG INT,
	CONSTRAINT PK_NV_MANV PRIMARY KEY(MANV),
	--CONSTRAINT FK_NV FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG),
	--CONSTRAINT FK_MA_NQL_MANV FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV)
)



CREATE TABLE DIADIEM_PHG(
	MAPH INT,
	DIADIEM CHAR(30),
	CONSTRAINT PK_1MAPHG_2DIADIEM PRIMARY KEY(MAPH, DIADIEM),
	--CONSTRAINT FK_MAPHG FOREIGN KEY(MAPH) REFERENCES PHONGBAN(MAPHG)
)

CREATE TABLE DEAN(
	TENDA CHAR(30),
	MADA INT,
	DDIEM_DA CHAR(100),
	PHONG INT,
	CONSTRAINT PK_DA_MADA PRIMARY KEY(MADA),
	--CONSTRAINT FK_DA FOREIGN KEY(PHONG) REFERENCES PHONGBAN(MAPHG)
)

CREATE TABLE PHANCONG(
	MA_NVIEN CHAR(3),
	SODA INT,
	THOIGIAN FLOAT,
	CONSTRAINT PK_PHANCONG_MA_1NVIEN_2SODA PRIMARY KEY(MA_NVIEN, SODA),
	--CONSTRAINT FK_PHANCONG FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV),
	--CONSTRAINT FK_PHANCONG1 FOREIGN KEY(SODA) REFERENCES DEAN(MADA)
)

CREATE TABLE THANNHAN(
	MA_NVIEN CHAR(3),
	TENTN CHAR(50),
	PHAI CHAR(5),
	NGSINH DATE,
	QUANHE CHAR(30),
	CONSTRAINT PK_TN_1TENTN_2MA_NVIEN PRIMARY KEY(TENTN, MA_NVIEN),
	--CONSTRAINT FK_TN FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)
)

INSERT INTO PHONGBAN(TENPHG, MAPHG, TRPHG, NG_NHANCHUC) VALUES
('Quan ly', 1, 888, '1971/06/19'),
('Dieu hanh', 4, 777, '1985/01/01'),
('Nghien cuu', 5, 333, '1978/05/22')

INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES
('Dinh', 'Ba', 'Tien', '123', '01/09/1955', '731 Tran Hung Dao Q1', 'Nam', 30000, '333', 5),
('Nguyen', 'Thanh', 'Tung', '333', '12/08/1945', '638 Nguyen Van Cu Q5', 'Nam', 40000, '888', 5),
('Tran', 'Thanh', 'Tam', '453', '07/31/1962', '543 Mai Thi luu Ba Dinh Ha', 'Nam', 25000, '333', 5),
('Nguyen', 'Manh', 'Hung', '666', '09/15/1952', '975 Le Lai P3 Vung Tau', 'Nam', 38000, '333', 5),
('Vuong', 'Ngoc', 'Quyen', '888', '10/10/1927', '450 Trung Vuong My Tho TG', 'Nu', 55000, '', 1),
('Le', 'Thi', 'Nhan', '987', '06/20/1931', '291 Ho Van Hue Q.PN', 'Nu', 43000, '888', 4),
('Tran', 'Hong', 'Quang', '777', '03/29/1959', '980 Le Hong Phong Vung Tau', 'Nam', 25000, '987', 4),
('Bui', 'Thuy', 'Vu', '999', '07/19/1958', '332 Nguyen Thai Hoc Quy', 'Nam', 25000, '987', 4)

INSERT INTO DIADIEM_PHG(MAPH, DIADIEM) VALUES
(1,'TP HCM'),
(4, 'HA NOI'),
(5, 'NHA TRANG'),
(5, 'TP HCM'),
(5, 'VUNG TAU')

INSERT INTO DEAN(TENDA, MADA, DDIEM_DA, PHONG) VALUES
('San pham X', 1, 'VUNG TAU', 5),
('San pham Y', 2, 'NHA TRANG', 5),
('San pham Z', 3, 'TP HCM', 5),
('Tin hoc hoa', 10, 'HA NOI', 4),
('Cap Quang', 20, 'TP HCM', 1),
('Dao tao', 30, 'HA NOI', 4)

INSERT INTO PHANCONG(MA_NVIEN, SODA, THOIGIAN) VALUES
('123', 1, 22.5),
('123', 2, 7.5),
('123', 3, 10),
('333', 10, 10),
('333', 20, 10),
('453', 1, 20),
('453', 2, 20),
('666', 3, 40),
('888', 20, 0),
('987', 20, 15),
('987', 30, 20),
('777', 10, 35),
('777', 30, 5),
('999', 10, 10),
('999', 30, 30)

INSERT INTO THANNHAN(MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE) VALUES
('123', 'Chau', 'Nu', '1978/12/31', 'Con gai'),
('123', 'Duy', 'Nam', '1978/01/01', 'Con trai'),
('123', 'Phuong', 'Nu', '1957/05/05', 'Vo chong'),
('333', 'Duong', 'Nu', '1948/05/03', 'Vo chong'),
('333', 'Tung', 'Nam', '1973/10/25', 'Con trai'),
('333', 'Quang', 'Nu', '1976/04/05', 'Con gai'),
('987', 'Dang', 'Nam', '1932/02/29', 'Vo chong')

ALTER TABLE NHANVIEN ADD
	CONSTRAINT FK_NV_PHG_MAPHG FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE NHANVIEN WITH NOCHECK ADD
	CONSTRAINT FK_NV_NQL FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV)

ALTER TABLE PHONGBAN ADD
	CONSTRAINT FK_PB_TRPHG_MANV FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)

ALTER TABLE DIADIEM_PHG ADD
	CONSTRAINT FK_DD_MAPH FOREIGN KEY(MAPH) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE DEAN ADD
	CONSTRAINT FK_PHONG_MAPHG FOREIGN KEY(PHONG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHANCONG ADD
	CONSTRAINT FK_SODA_MADA FOREIGN KEY(SODA) REFERENCES DEAN(MADA),
	CONSTRAINT FK_MA_NVIEN_MANV FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)

ALTER TABLE THANNHAN ADD
	CONSTRAINT FK_TN_MA_NVIEN_MANV FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)


--CAU 1: 
SELECT *
FROM NHANVIEN
WHERE PHG = 4

--CAU 2:
SELECT *
FROM NHANVIEN
WHERE LUONG>30000

--CAU 3:
SELECT *
FROM NHANVIEN
WHERE (LUONG>25000 AND PHG = 4) OR (LUONG>30000 AND PHG = 5) 

--CAU 4:
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN NV, DIADIEM_PHG DDP
WHERE NV.PHG=DDP.MAPH AND DDP.DIADIEM = 'TP HCM'

--CAU 5:
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN NV
WHERE NV.HONV LIKE 'N%'

--CAU 6:
SELECT DAY(NGSINH)AS 'NGAY SINH', DCHI
FROM NHANVIEN NV
WHERE NV.HONV = 'Dinh' AND NV.TENLOT = 'Ba' AND NV.TENNV = 'Tien'

--CAU 7:
SELECT *
FROM NHANVIEN NV
WHERE 1960 <= YEAR(NGSINH) AND YEAR(NGSINH) <= 1965

--CAU 8:
SELECT HONV, TENLOT, TENNV, YEAR(NGSINH) AS 'NAM SINH'
FROM NHANVIEN

--CAU 9:
SELECT HONV, TENLOT, TENNV, 2022-YEAR(NGSINH) AS 'TUOI'
FROM NHANVIEN

--CAU 10:
SELECT TENPHG, DIADIEM
FROM PHONGBAN PB, DIADIEM_PHG DD
WHERE DD.MAPH = PB.MAPHG

--CAU 11:
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN NV, PHONGBAN PB
WHERE NV.MANV = PB.TRPHG

--CAU 12:
SELECT HONV, TENLOT, TENNV, DCHI
FROM NHANVIEN NV, PHONGBAN PB
WHERE PB.TENPHG = 'Nghien cuu' AND NV.PHG = PB.MAPHG

--CAU 13:
SELECT TENDA, TENPHG, HONV, TENLOT, TENNV, NG_NHANCHUC
FROM NHANVIEN NV, PHONGBAN PB, DEAN DA
WHERE DA.PHONG = PB.MAPHG AND DA.DDIEM_DA = 'HA NOI' AND PB.TRPHG = NV.MANV

--CAU 14:
SELECT HONV, TENLOT, TENNV, TENTN
FROM NHANVIEN NV, THANNHAN TN
WHERE NV.PHAI = 'Nu' AND TN.MA_NVIEN = NV.MANV

--CAU 15:
SELECT NV.HONV, NV.TENLOT, NV.TENNV, NQL.HONV AS 'NQL', NQL.TENLOT AS 'NQL', NQL.TENNV AS 'NQL'
FROM NHANVIEN NV, NHANVIEN NQL
WHERE NV.MA_NQL = NQL.MANV

--CAU 16:
SELECT NV.HONV, NV.TENLOT, NV.TENNV, TP.HONV AS 'TP', TP.TENLOT AS 'TP', TP.TENNV AS 'TP'
FROM NHANVIEN NV, PHONGBAN PB, NHANVIEN TP
WHERE NV.PHG = PB.MAPHG AND PB.TRPHG = TP.MANV

--CAU 17:
SELECT NV.HONV, NV.TENLOT, NV.TENNV
FROM NHANVIEN NV, PHANCONG PC, DEAN DA, NHANVIEN NQL
WHERE DA.MADA = PC.SODA AND NV.MANV = PC.MA_NVIEN AND DA.TENDA = 'San pham X' 
	AND NV.PHG = 5 AND NQL.HONV = 'Nguyen' AND NQL.TENLOT = 'Thanh' AND NQL.TENNV = 'Tung'

--CAU 18:
SELECT TENDA
FROM DEAN DA, NHANVIEN NV, PHANCONG PC
WHERE PC.MA_NVIEN = NV.MANV AND DA.MADA = PC.SODA AND NV.HONV='Dinh' AND NV.TENLOT='Ba' AND NV.TENNV = 'Tien'

--CAU 19:
SELECT COUNT(TENDA) AS 'SO LUONG DA CUA CONG TY'
FROM DEAN DA

--CAU 20:
SELECT COUNT(TENDA) AS 'SO LUONG DE AN'
FROM PHONGBAN PB, DEAN DA
WHERE PB.MAPHG = DA.PHONG AND PB.TENPHG = 'Nghien cuu'

--CAU 21:
SELECT AVG(LUONG) AS 'LUONG TRUNG BINH'
FROM NHANVIEN NV
WHERE NV.PHAI = 'Nu'

--CAU 22:
SELECT COUNT(TENTN) AS 'SO THAN NHAN'
FROM NHANVIEN NV, THANNHAN TN
WHERE NV.MANV = TN.MA_NVIEN AND NV.HONV = 'Dinh' AND NV.TENLOT = 'Ba' AND NV.TENNV = 'Tien'

--CAU 23:
